FROM python:3.11.1

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

RUN pip install pipenv \
    && pipenv run pip freeze > requirements.txt

COPY requirements.txt /code/

RUN pipenv install -r requirements.txt --deploy 

COPY . /code/

CMD ["./entrypoint.sh"]