version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - redis
    links:
      - redis

  redis:
    image: redis:latest
