version: "3"

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "6666:6666"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:latest
