FROM python:3.11.1

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY Pipfile Pipfile.lock /code/

RUN pip install pipenv && pipenv install --dev --system --deploy --ignore-pipfile

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
